celestiaorg/nmt

fuzz_test.go
internal/hasher.go
internal/hasher_test.go
internal/nmt_hasher.go
namespace/data.go
namespace/digest.go
namespace/digest_test.go
namespace/id.go
namespace/size.go
nmt.go
nmt_test.go
proof.go
proof_test.go

implements and closes #8 
Also tackles setting the init. capacity for internal slices as an option (see comment/discussion: https://github.com/lazyledger/nmt/pull/3#discussion_r467980031)

Optionally ignore max namespace ID

---

namespace/data.go

Instead the ID returned by the data has a size, hence Data.ID().Size() is used everywhere anyways

remove obsolete method Data.NamespaceSize

---

nmt.go
nmt_test.go

Adds an _optional_ "NodeVisitor" function to the tree that will be called on each node of the tree.
This can be used to tackle #9, and can also be used in the IPLD-plugin. It might also be useful to inspect/debug the tree, or, to print-out the tree in different ways.

Add possibility to traverse inner nodes

---

namespace/digest.go
namespace/digest_test.go
nmt.go
proof.go

Remove panic from IntervalDigestFromBytes

---

namespace/digest.go
namespace/digest_test.go

Otherwise, a user has to implement it himself using Bytes() what would cause him to make unnecessary allocations

Implement Equal for IntervalDigest

---

nmt_test.go

This fixes another minor glitch that was introduced by changing the Push method signature in #27. Similar to what @evan-forbes found in https://github.com/lazyledger/nmt/pull/27#discussion_r598746721
Followup to / part of #26.

Fix minor refactoring glitch introduced with #27

---

namespace/digest.go

https://github.com/lazyledger/lazyledger-core/pull/248#issuecomment-809595268

Fix nasty append bug that caused 'min' namespace id modifications 

---

namespace/digest.go
namespace/digest_test.go
nmt_test.go
proof.go

Some [tests](https://github.com/lazyledger/lazyledger-core/blob/59ceaf8c44a069a55d5f8f8f3bea50b23a186146/rpc/client/evidence_test.go#L115) in lazyledger-core require `DataAvailabilityHeader` to be encoded via json, this PR exports the fields of IntervalDigest, along with adding appropriate json tags.
This PR, or another alternative, should be merged before [#312](https://github.com/lazyledger/lazyledger-core/pull/312) can be merged.
closes #34

Make `IntervalDigest` jsonable

---

fuzz_test.go
hasher.go
hasher_test.go
nmt.go
nmt_test.go
proof.go
proof_test.go

After reviewing https://github.com/lazyledger/lazyledger-core/pull/351 I've realized that #38 introduced an unnecessary alloc per leaf and inner node. 
This PR reverts the changes of #38, caches the root s.t. it only gets computed when necessary but keeps that test that aims to reproduce the issue in #37. (draft as I want to confirm this really does not re-introduce the issue in test withing ll-core, too https://github.com/lazyledger/lazyledger-core/commit/152202137455450f971df5c7294380714dcc7ac6)

Reuse hash 

---

nmt.go
nmt_test.go
proof.go

This PR exports the `MinNamespace` and `MaxNamespace` functions so that we can use them in the `celestia-node` repo instead of directly copying the functionality.

nmt.go: export Min/MaxNamespace functions so we can use them in celestia-node

---

fuzz_test.go
nmt_test.go
proof.go
proof_test.go

building on #57, we also need to be able to verify inclusion proofs for arbitrary ranges of leaves. 
Note: this PR is API breaking and will require another version bump

Verify inclusion proofs with multiple leaves

---

hasher.go
proof.go
proof_test.go

Use the same recursive approach as in `nmt.Root()` to verify leaf hashes
Removes the dependency on `Celestiaorg/merkletree` in proof verification
Fixes half of the issue mentioned in #15

Remove dependency on nebulous in verification

---

subrootpaths.go

This change fixes the use of expensive code that used math.Pow(float(2), N) but really that's expensive code that could be simplified by using left bitshifts.
The improvements in speed show in benchmarks:
```shell
$ benchstat before.txt after.txt
name    old time/op    new time/op    delta
Pow2-8     322ns ± 2%     114ns ± 1%  -64.69%  (p=0.000 n=9+8)
name    old alloc/op   new alloc/op   delta
Pow2-8     40.0B ± 0%     40.0B ± 0%     ~     (all equal)
name    old allocs/op  new allocs/op  delta
Pow2-8      5.00 ± 0%      5.00 ± 0%     ~     (all equal)
```
Fixes #72

prune: speed up using 1<<N instead of math.Pow(2, N)

---

subrootpaths.go

Performs bounds checks to avoid out of bounds panics and instead return nil values.
This change uses the much simpler bits.Len(N)-1
instead of math.Log2(N) which is much more expensive and more error prone to use.
Fixes #77

prune, subdivide: check bounds and use bits.Len instead of math.Log2 to determine bits for width

---

namespace/doc.go

- Link to types
- Remove IntervalDigest because it doesn't exist in this package

docs: improve namespace doc

---

subrootpaths.go
subrootpaths_test.go

This change cautiously checks addition results to prevent integer overflows. Also checks errors from left and right GetSubrootPaths generation to avoid any future runtime panics. While here, also slightly tweaked table tests for TestPathGeneration to use subtests and report which case failed exactly.

nmt: sanity check addition results to avoid overflows

---

nmt_test.go
proof.go

- Reject empty "proofs" of absence, except in the special case where the root doesn't cover the namespace being proved
- Add test case to catch regression
- Add test case to ensure that the absence of the zero namespace can be proved against the empty tree
closes #86

Bug fix: reject forged proofs of absence. Fixes (#86)

---

hasher.go

While reviewing the nmt codebase (as part of this [EPIC](https://github.com/celestiaorg/celestia-app/issues/1296)) I realized the description of the `HashLeaf` function does not match its implementation (w.r.t. referred variable names) which causes confusion when comprehending the code.  This PR aims to correct and revise that description. 
Also, the illustration of an nmt provided in the [Readme file](https://github.com/celestiaorg/nmt/blob/master/README.md) seems not aligned with the leaf hash calculation, where in the `node_0.0` the `d_0.0=H(data_0)` while it should be `d_0.0=H(0x00, nid_0, data_0)`. I was not able to edit the image as its source code is not available.

chore: fixes the HashLeaf description

---

hasher.go

This PR fixes the bug included in the last release, that resulted (silently) in producing a different hash than the original hasher.
Related: 
https://github.com/celestiaorg/celestia-core/pull/954
https://github.com/celestiaorg/celestia-node/pull/1651

fix: use `baseHasher.Size` for `sha256Len` instead of `n.Size`

---

hasher.go
hasher_test.go

The following two functions `Sha256Namespace8FlaggedLeaf` and `Sha256Namespace8FlaggedInner` are part of the public APIs, however, they are no longer needed as mentioned by @liamsi in https://github.com/celestiaorg/nmt/issues/87#issuecomment-1355165925. I also verified it against the main branch and the latest release (v0.7.0-rc4@8b9937f) of celestia-node codebase and no usage was found. Likewise, no usage was available in the clestia-core repo.
**Summary of changes:**
- This PR deletes these `Sha256Namespace8FlaggedLeaf` and `Sha256Namespace8FlaggedInner` functions and the relevant tests.
- After performing this update, it was found that there was no longer any use case for the `defaultHasher` in the main hasher file, and it is now only being used in the test file. As a result, it has …

chore!: remove unused API functions Sha256Namespace8FlaggedLeaf and Sha256Namespace8FlaggedInner from the hasher

---

nmt.go
nmt_test.go

Closes https://github.com/celestiaorg/nmt/issues/104

feat: implement nmt methods Min/MaxNamespace

---

my_test.go
spec/nmt.md

This pull request aligns with the https://github.com/celestiaorg/celestia-app/issues/1296 EPIC and introduces an NMT specification that includes a description of NMT as a data structure, an explanation of the NMT library, and a sample code. In terms of description of the NMT library, the focus was on the portions that are used in the NMT wrapper to establish the foundation for the NMT wrapper specification. The NMT methods are illustrated through a running code example that was originally included in the Readme file of the NMT repository (with a minor change in namespace ID of one of the leaves in order to be able to provide an example of absence proof). This example has been expanded to provide a more detailed description of each method call, an interpretation of the parameters, and its …

chore: NMT specifications

---

nmt.go
proof.go

This PR intends to bring the description of the `leafHash` field in the `Proof `data structure in line with the specification. Additionally, among the three criteria enumerated for the `leafHash` the third criterion  is redundant since it is already covered by the first two. Although this has already been addressed in the specification, the code description needs to be updated, and this PR accomplishes that (this comment was originally raised in https://github.com/celestiaorg/nmt/issues/110#issuecomment-1448413024).

chore: fixes the description of the index of leafHash in the absence proof

---

nmt.go

Addresses https://github.com/informalsystems/audit-celestia/issues/40.

chore: fixes the description of absence index in the calculateAbsenceIndex

---

proof.go
proof_test.go
spec/nmt.md

Addresses the issue set out in #115.

feat:  check the namespace ID range of the leafHash in an absence proof to ensure soundness

---

docs/nmt-lib.md
docs/spec/nmt.md

Closes https://github.com/celestiaorg/nmt/issues/112 and https://github.com/informalsystems/audit-celestia/issues/41.
Also, partially addresses https://github.com/celestiaorg/nmt/issues/106.

chore: splits the nmt spec into two files and moves them into separate directories

---

README.md
go.mod
go.sum
proof_test.go

Inline with #125.
For more context, please see the following [comment](https://github.com/celestiaorg/nmt/issues/125#issuecomment-1461047495).

chore: removes the usage of the merkletree package

---

docs/nmt-lib.md
hasher.go

This PR rephrases the explanation on how the namespace range is calculated when the parameter `IgnoreMaxNamespace` is set. If merged, it will close #133 . 
I tried to simplify sentences explaining the logic and add a precise expression at the end of the explanation.
[rendered document](https://github.com/ivan-gavran/nmt/blob/ivan/ignoreMaxNsExplanation/docs/nmt-lib.md)

Reworded explanation of calculating namespace when IgnoreMaxNamespace is set 

---

fuzz_test.go
hasher.go
hasher_test.go
nmt.go
nmt_test.go
proof.go
proof_test.go

Closes #109 and #99.
This pull request ensures that the `HashNode` and `HashLeaf` functions return errors instead of panicking, and that caller functions properly handle any emitted errors. When generating proofs, any hashing errors are propagated with additional context. During verification, hashing errors are treated as unsuccessful proof verification.
Note that in this PR, the term `Irrecoverable errors` used to describe errors that any number of retries can correct the them.

feat!:  updates the HashNode and HashLeaf methods to return error instead of panic and refactors the code

---

nmt.go

Closes https://github.com/celestiaorg/nmt/issues/123

fix: ProveNamespace godoc

---

docs/spec/nmt.md
nmt.go

chore: incorporates index-based Merkle range proof in the NMT specification

---

hasher.go
hasher_test.go
nmt.go
nmt_test.go
proof_test.go

Closes #108  and https://github.com/celestiaorg/nmt/issues/143

feat:  compute leaf hashes in the Push method

---

nmt_test.go
proof.go
proof_test.go

Closes https://github.com/celestiaorg/nmt/issues/132

chore: introduces a generic function to generate sample NMTs

---

hasher.go
hasher_test.go

Closes #153 (part of https://github.com/celestiaorg/nmt/issues/173)

feat!: checks the exact size of the node in HashNode

---

proof.go
proof_test.go

feat: checks that all the arguments of VerifyNamespace conform to the same namespace hash format

---

proof.go
proof_test.go

Resolves https://github.com/celestiaorg/nmt/issues/164

feat!: rejects invalid empty range proofs

---

proof.go
proof_test.go

Closes https://github.com/celestiaorg/nmt/issues/178

feat: export `VerifyLeafHashes`

---

nmt.go

feat: adds the Size() method to the nmt API

---

hasher.go

chore: replaces redundant codes in the HashNode with a proper function call

---

proof.go
proof_test.go

Closes #181
The updates made by this PR will result in a breaking change, as empty proofs with a non-empty `leafHash` field will no longer be considered valid. This means that their verification through `VerifyNamespace` will fail.
Example:
```go
nIDSize := 1
tree := exampleNMT(nIDSize, 1, 2, 3, 4)
root, err := tree.Root()
require.NoError(t, err)
hasher := 
proof := Proof{
start:    0,
end:      0,
nodes:    nil,
leafHash: tree.leafHashes[0],
}
res := proof.VerifyNamespace(tree.treeHasher.baseHasher, []byte{0}, [][]byte{}, root)
require.True(res) // this is false with the changes in this PR, however, previously, it was true
```

feat!: add an additional constraint of empty leafHash field to the empty proof definition

---

docs/nmt-lib.md

This PR brings the description of the IgnoreMaxNamespace flag in parity with the implementation.

chore: aligns the Ignore Max Namespace description with the implementation

---

namespace/id.go
namespace/id_test.go

Implements https://github.com/celestiaorg/nmt/issues/200

Add HexString method for namespace id

---

nmt_test.go

Previously the function `ExampleNamespacedMerkleTree` existed in nmt_test.go. AFAIK Go only runs unit tests for functions with the name `Test*` so I wouldn't expect `ExampleNamespacedMerkleTree` to run by the Go test runner. But it is run and fails [here](https://github.com/celestiaorg/nmt/actions/runs/5092193098/jobs/9153228914?pr=202#step:7:551).
This PR converts the example into a test. Defer to @staheri14 if it should be deleted instead.

test: ExampleNamespacedMerkleTree

---

namespace/id.go
namespace/id_test.go

This PR contains a breaking change that implements https://github.com/celestiaorg/nmt/pull/201#issuecomment-1564414023. Relevant https://github.com/celestiaorg/nmt/issues/200

feat!: hex encode `id.String()` output

---

hasher.go
hasher_test.go
nmt.go
nmt_test.go
proof.go
proof_test.go

Currently, the hasher is not swappable, this is only problematic when trying to create fraudulent block test cases, since the standard hasher prevents such behavior.

feat: prepare for testing fraudulant blocks by allowing for custom hashers and the ability to add leaves without validation

---

proof.go
proof_test.go

Adds json marshaling/unmarshaling to `nmt.Proof`.
As found elsewhere in the go stdlib, `UnmarshalJSON` must be defined on the pointer receiver although `MarshalJSON` is a value receiver. 
This is needed because the fields are private. Does this need to be the case? If we make them public, JSON marshaling will work by default.

feat(proof.go): adding JSON marshal/unmarshal

---

docs/spec/nmt.md

Closes #205 
Additionally, in line with [this](https://github.com/celestiaorg/nmt/issues/206), to ensure consistency with how **namespace ID** and **namespace** (i.e., a combination of namespace ID and version) are utilized in the core-app, I have replaced all instances of words that refer to or imply **namespace ID** with the more accurate term "**namespace**".

doc: introduces short namespace absence proof in the NMT specs

---

README.md
docs/nmt-lib.md

doc: aligns the nmt API doc with the current implementation

---

proof.go
proof_test.go

After investigating the current implementation, verified that the nmt library is capable of verifying short absence proofs. This PR contains the necessary tests to demonstrate and test this capability.
In line with #210

test: incorporates tests for short absence proof verification 

---

proof.go

jsonProof is not necessary when we already have pb.Proof, which caused issues because of mismatching field names.
Related: https://github.com/celestiaorg/celestia-node/issues/2631
Specifically: https://github.com/celestiaorg/celestia-node/issues/2631#issuecomment-1708048715

fix: replacing jsonProof with pb.Proof

---

.github/workflows/go.yml

Closes https://github.com/celestiaorg/nmt/issues/250
@staheri14 noticed rate limiting in CI when sending data to CODECOV. This uses the org wide secret to ensure we are free from public usage/rate limiting

ci: add secrets.CODECOV_TOKEN to codecov 

---

README.md

The status badge for the the golangci-lint workflow fails to load. This PR fixes the link and resolves the issue.

chore: fixes dead link for golangci-lint status badge in README

---

proof.go

Use `popIfNonEmpty` instead of manual advancement of slice.

refactor: popIfNonEmpty for  leaf hashes

---

nmt.go

To reduce number of allocations, we can directly return precomputed leafs (without copying them).
```
$ go-perftuner benchstat before.txt after.txt
name                       old time/op    new time/op    delta
ComputeRoot/64-leaves-16      115µs ± 1%     112µs ± 0%   -2.80%  (p=0.008 n=5+5)
ComputeRoot/128-leaves-16     230µs ± 5%     223µs ± 1%        ~  (p=0.016 n=5+5)
ComputeRoot/256-leaves-16     456µs ± 1%     446µs ± 1%        ~  (p=0.008 n=5+5)
ComputeRoot/20k-leaves-16    49.7ms ± 1%    48.5ms ± 3%        ~  (p=0.095 n=5+5)
name                       old alloc/op   new alloc/op   delta
ComputeRoot/64-leaves-16     30.4kB ± 0%    27.4kB ± 0%  -10.09%  (p=0.008 n=5+5)
ComputeRoot/128-leaves-16    54.3kB ± 0%    48.1kB ± 0%  -11.32%  (p=0.008 n=5+5)
ComputeRoot/256-leaves-16 …
```

perf: avoid redundant slice allocation in leafHash assignment

---

.github/dependabot.yml

Motivation: https://github.com/celestiaorg/nmt/pull/302#issuecomment-3255676292
idk who removed the dependency label from this repo but IMO it is already clear that dependabot PRs are to update dependencies so the label doesn't add any value.

ci: remove dependency label

---

hasher.go
hasher_test.go
nmt.go
nmt_test.go

**This PR introduces an option `ReuseBuffers`** which will enable the `NamespacedMerkleTree` and the `NmtHasher` to reuse the buffers. The pipeline looks like this (if the option is enabled):
- on first run we use the hasher normally, but underneath it tracks all the slices allocated for hashes
- after we call `Reset` on nmt, the buffers are reset and the previously allocated slices are available for reuse
- the next time the allocations will not happen.
This gives us roughly 15% performance gains when used repeatedly, results in 3x less memory used and 95% less allocations.
**If the option is not enabled, the tree functionality is not affected.**
```
cpu: Apple M1 Max
BenchmarkNMTReuseVsNoReuse
BenchmarkNMTReuseVsNoReuse/128-leaves-Root-NoReuse …
```

perf: reuse buffer for hashes (root calculation and leaves push)
